-- @ScriptType: ModuleScript
return function(Constants)
	return {
		-- Inventory
		Extra_00 = {
			Id = "Extra_00",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=0",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_01 = {
			Id = "Extra_01",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524033921",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_02 = {
			Id = "Extra_02",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524095170",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_03 = {
			Id = "Extra_03",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524022743",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_04 = {
			Id = "Extra_04",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524023928",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_05 = {
			Id = "Extra_05",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523972935",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_06 = {
			Id = "Extra_06",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801785860",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_07 = {
			Id = "Extra_07",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523974768",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_08 = {
			Id = "Extra_08",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523959919",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_09 = {
			Id = "Extra_09",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801786177",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_10 = {
			Id = "Extra_10",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524024766",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_11 = {
			Id = "Extra_11",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524089033",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_12 = {
			Id = "Extra_12",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524087633",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_13 = {
			Id = "Extra_13",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524098445",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_14 = {
			Id = "Extra_14",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524094387",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_15 = {
			Id = "Extra_15",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524095759",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_16 = {
			Id = "Extra_16",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524097791",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_17 = {
			Id = "Extra_17",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524025411",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_18 = {
			Id = "Extra_18",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524068937",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_19 = {
			Id = "Extra_19",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524086120",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_20 = {
			Id = "Extra_20",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524023366",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_21 = {
			Id = "Extra_21",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524057611",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_22 = {
			Id = "Extra_22",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524089611",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_23 = {
			Id = "Extra_23",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801786990",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_24 = {
			Id = "Extra_24",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524056624",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_25 = {
			Id = "Extra_25",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524093815",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_26 = {
			Id = "Extra_26",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524097055",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_27 = {
			Id = "Extra_27",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524096384",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_28 = {
			Id = "Extra_28",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524049825",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_29 = {
			Id = "Extra_29",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524058219",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
		Extra_30 = {
			Id = "Extra_30",
			Name = " ",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3524032382",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Extra,
		},
	}
end
