-- @ScriptType: ModuleScript
return function(Constants)
	return {
		Eyebrow_01 = {
			Id = "Eyebrow_01",
			Name = "Eyebrow_01",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801687922",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_02 = {
			Id = "Eyebrow_02",
			Name = "Eyebrow_02",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801687635",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_03 = {
			Id = "Eyebrow_03",
			Name = "Eyebrow_03",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801716156",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_04 = {
			Id = "Eyebrow_04",
			Name = "Eyebrow_04",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523931787",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_05 = {
			Id = "Eyebrow_05",
			Name = "Eyebrow_05",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801716326",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_06 = {
			Id = "Eyebrow_06",
			Name = "Eyebrow_06",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523931344",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_07 = {
			Id = "Eyebrow_07",
			Name = "Eyebrow_07",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523930715",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_08 = {
			Id = "Eyebrow_08",
			Name = "Eyebrow_08",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801696705",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_09 = {
			Id = "Eyebrow_09",
			Name = "Eyebrow_09",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801688112",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_10 = {
			Id = "Eyebrow_10",
			Name = "Eyebrow_10",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=3523932495",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
		Eyebrow_11 = {
			Id = "Eyebrow_11",
			Name = "Eyebrow_11",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801697005",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Eyebrows,
		},
	}
end
