-- @ScriptType: ModuleScript
return function(Constants)
	return {
		Hair_00 = {
			Id = "Hair_00",
			Name = "",
			Price = 0,
			ProductId = 0,
			Image = "rbxthumb://type=Asset&id=".."0".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		
		Hair_01 = {
			Id = "Hair_01",
			Name = "",
			Price = 60,
			ProductId = 91599957937820,
			Image = "rbxthumb://type=Asset&id=".."91599957937820".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_02 = {
			Id = "Hair_02",
			Name = "Uncharted Brown Hair",
			Price = 60,
			ProductId = 131497912946164,
			Image = "rbxthumb://type=Asset&id=".."131497912946164".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_03 = {
			Id = "Hair_03",
			Name = "Black Messy Anime Hair",
			Price = 60,
			ProductId = 122956206700572,
			Image = "rbxthumb://type=Asset&id=".."122956206700572".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_04 = {
			Id = "Hair_04",
			Name = "Brown Messy Anime hair 9.0",
			Price = 60,
			ProductId = 117494677159091,
			Image = "rbxthumb://type=Asset&id=".."117494677159091".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_05 = {
			Id = "Hair_05",
			Name = "Brown Sharp Messy Anime Hair",
			Price = 60,
			ProductId = 11068150682,
			Image = "rbxthumb://type=Asset&id=".."11068150682".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_06 = {
			Id = "Hair_06",
			Name = "Brown Charmer Hair",
			Price = 60,
			ProductId = 376548738,
			Image = "rbxthumb://type=Asset&id=".."376548738".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_07 = {
			Id = "Hair_07",
			Name = "Beautiful Hair for Beautiful People",
			Price = 95,
			ProductId = 16630147,
			Image = "rbxthumb://type=Asset&id=".."16630147".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_08 = {
			Id = "Hair_08",
			Name = "Trecky Hair",
			Price = 60,
			ProductId = 32278814,
			Image = "rbxthumb://type=Asset&id=".."32278814".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_09 = {
			Id = "Hair_09",
			Name = "Crazy Game Dev Hair",
			Price = 150,
			ProductId = 248286896,
			Image = "rbxthumb://type=Asset&id=".."248286896".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_10 = {
			Id = "Hair_10",
			Name = "Auburn Scene Hair",
			Price = 100,
			ProductId = 62246484,
			Image = "rbxthumb://type=Asset&id=".."62246484".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_11 = {
			Id = "Hair_11",
			Name = "Black Manga Hero Hair",
			Price = 75,
			ProductId = 398672920,
			Image = "rbxthumb://type=Asset&id=".."398672920".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_12 = {
			Id = "Hair_12",
			Name = "Samurai Hair",
			Price = 60,
			ProductId = 21635620,
			Image = "rbxthumb://type=Asset&id=".."21635620".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_13 = {
			Id = "Hair_13",
			Name = "Pigtails",
			Price = 60,
			ProductId = 14276180507,
			Image = "rbxthumb://type=Asset&id=".."14276180507".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_14 = {
			Id = "Hair_14",
			Name = "High Fashion Sleek Short Bob in Black",
			Price = 60,
			ProductId = 12564647277,
			Image = "rbxthumb://type=Asset&id=".."12564647277".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_15 = {
			Id = "Hair_15",
			Name = "White Cute Bunned Hair",
			Price = 60,
			ProductId = 18229109342,
			Image = "rbxthumb://type=Asset&id=".."18229109342".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_16 = {
			Id = "Hair_16",
			Name = "Red Anime Girl Hair",
			Price = 60,
			ProductId = 17403085369,
			Image = "rbxthumb://type=Asset&id=".."17403085369".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_17 = {
			Id = "Hair_17",
			Name = "Official Katara Hair - Avatar: The Last Airbender",
			Price = 60,
			ProductId = 16560449448,
			Image = "rbxthumb://type=Asset&id=".."16560449448".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_18 = {
			Id = "Hair_18",
			Name = "Black - Anime Slicked Back Hair (Short Version)",
			Price = 60,
			ProductId = 133232372409812,
			Image = "rbxthumb://type=Asset&id=".."133232372409812".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		
		-- Free Items
		Hair_19 = {
			Id = "Hair_19",
			Name = "",
			Price = 0,
			ProductId = 62234425,
			Image = "rbxthumb://type=Asset&id=".."62234425".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},	
		Hair_20 = {
			Id = "Hair_20",
			Name = "",
			Price = 0,
			ProductId = 376526888,
			Image = "rbxthumb://type=Asset&id=".."376526888".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_21 = {
			Id = "Hair_21",
			Name = "",
			Price = 0,
			ProductId = 9244111257,
			Image = "rbxthumb://type=Asset&id=".."9244111257".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_22 = {
			Id = "Hair_22",
			Name = "",
			Price = 0,
			ProductId = 2956239660,
			Image = "rbxthumb://type=Asset&id=".."2956239660".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
		Hair_23 = {
			Id = "Hair_23",
			Name = "",
			Price = 0,
			ProductId = 376524487,
			Image = "rbxthumb://type=Asset&id=".."376524487".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Hair,
		},
	}
end
