-- @ScriptType: ModuleScript
return function(Constants)
	return {
		Jersey_00 = {
			Id = "Jersey_00",
			Name = "Jersey",
			Price = 0,
			ProductId = 0, --7123903816,
			Image = "rbxthumb://type=Asset&id=".."7123903816".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_01 = {
			Id = "Jersey_01",
			Name = "Jersey",
			Price = 10,
			ProductId = 55314019,
			Image = "rbxthumb://type=Asset&id=".."55314019".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_02 = {
			Id = "Jersey_02",
			Name = "Jersey",
			Price = 5,
			ProductId = 6461441413,
			Image = "rbxthumb://type=Asset&id=".."6461441413".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_03 = {
			Id = "Jersey_03",
			Name = "Jersey",
			Price = 7,
			ProductId = 16936083122,
			Image = "rbxthumb://type=Asset&id=".."16936083122".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_04 = {
			Id = "Jersey_04",
			Name = "Jersey",
			Price = 10,
			ProductId = 5678240204,
			Image = "rbxthumb://type=Asset&id=".."5678240204".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		
		Jersey_05 = {
			Id = "Jersey_05",
			Name = "Jersey",
			Price = 7,
			ProductId = 16756601952,
			Image = "rbxthumb://type=Asset&id=".."16756601952".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_06 = {
			Id = "Jersey_06",
			Name = "Jersey",
			Price = 5,
			ProductId = 6825074988,
			Image = "rbxthumb://type=Asset&id=".."6825074988".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_07 = {
			Id = "Jersey_07",
			Name = "Jersey",
			Price = 7,
			ProductId = 16790789610,
			Image = "rbxthumb://type=Asset&id=".."16790789610".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_08 = {
			Id = "Jersey_08",
			Name = "Jersey",
			Price = 7,
			ProductId = 17111260286,
			Image = "rbxthumb://type=Asset&id=".."17111260286".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_09 = {
			Id = "Jersey_09",
			Name = "Jersey",
			Price = 5,
			ProductId = 17824079522,
			Image = "rbxthumb://type=Asset&id=".."17824079522".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_10 = {
			Id = "Jersey_10",
			Name = "Jersey",
			Price = 5,
			ProductId = 16926065129,
			Image = "rbxthumb://type=Asset&id=".."16926065129".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_11 = {
			Id = "Jersey_11",
			Name = "Jersey",
			Price = 5,
			ProductId = 17507097551,
			Image = "rbxthumb://type=Asset&id=".."17507097551".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_12 = {
			Id = "Jersey_12",
			Name = "Jersey",
			Price = 5,
			ProductId = 16863826488,
			Image = "rbxthumb://type=Asset&id=".."16863826488".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_13 = {
			Id = "Jersey_13",
			Name = "Jersey",
			Price = 5,
			ProductId = 17507097551,
			Image = "rbxthumb://type=Asset&id=".."17507097551".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
		Jersey_14 = {
			Id = "Jersey_14",
			Name = "Jersey",
			Price = 8,
			ProductId = 17769497734,
			Image = "rbxthumb://type=Asset&id=".."17769497734".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Jersey,
		},
	}
end