-- @ScriptType: ModuleScript
return function(Constants)
	return {
		Mouth_01 = {
			Id = "Mouth_01",
			Name = "Mouth_01",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801778560",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_02 = {
			Id = "Mouth_02",
			Name = "Mouth_02",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801778896",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_03 = {
			Id = "Mouth_03",
			Name = "Mouth_03",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2813767341",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_04 = {
			Id = "Mouth_04",
			Name = "Mouth_04",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801759987",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_05 = {
			Id = "Mouth_05",
			Name = "Mouth_05",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801759774",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_06 = {
			Id = "Mouth_06",
			Name = "Mouth_06",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801760198",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_07 = {
			Id = "Mouth_07",
			Name = "Mouth_07",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801767539",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_08 = {
			Id = "Mouth_08",
			Name = "Mouth_08",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801731770",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_09 = {
			Id = "Mouth_09",
			Name = "Mouth_09",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801751305",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_10 = {
			Id = "Mouth_10",
			Name = "Mouth_10",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801768094",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_11 = {
			Id = "Mouth_11",
			Name = "Mouth_11",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2818152574",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_12 = {
			Id = "Mouth_12",
			Name = "Mouth_12",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2813765960",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_13 = {
			Id = "Mouth_13",
			Name = "Mouth_13",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801742053",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_14 = {
			Id = "Mouth_14",
			Name = "Mouth_14",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2818152352",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_15 = {
			Id = "Mouth_15",
			Name = "Mouth_15",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801778269",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_16 = {
			Id = "Mouth_16",
			Name = "Mouth_16",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801732091",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_17 = {
			Id = "Mouth_17",
			Name = "Mouth_17",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801741665",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_18 = {
			Id = "Mouth_18",
			Name = "Mouth_18",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801751773",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_19 = {
			Id = "Mouth_19",
			Name = "Mouth_19",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801751501",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_20 = {
			Id = "Mouth_20",
			Name = "Mouth_20",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801767831",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_21 = {
			Id = "Mouth_21",
			Name = "Mouth_21",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801732538",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_22 = {
			Id = "Mouth_22",
			Name = "Mouth_22",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2818152743",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_23 = {
			Id = "Mouth_23",
			Name = "Mouth_23",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2813766627",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_24 = {
			Id = "Mouth_24",
			Name = "Mouth_24",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2801741881",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
		Mouth_25 = {
			Id = "Mouth_25",
			Name = "Mouth_25",
			Description = " ",
			Image = "http://www.roblox.com/asset/?id=2818152144",
			CurrencyType = Constants.CurrencyTypes.Gems,
			InventoryType = Constants.InventoryType.Styling,
			ItemType = Constants.ItemType.Mouth,
		},
	}
end
