-- @ScriptType: ModuleScript
return function(Constants)
	return {
		Pant_00 = {
			Id = "Pant_00",
			Name = "Pant",
			Price = 0,
			ProductId = 0,--12176104895,
			Image = "rbxthumb://type=Asset&id=".."12176104895".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Free,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_01 = {
			Id = "Pant_01",
			Name = "Pant",
			Price = 10,
			ProductId = 1087842291,
			Image = "rbxthumb://type=Asset&id=".."1087842291".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_02 = {
			Id = "Pant_02",
			Name = "Pant",
			Price = 10,
			ProductId = 17208278838,
			Image = "rbxthumb://type=Asset&id=".."17208278838".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_03 = {
			Id = "Pant_03",
			Name = "Pant",
			Price = 5,
			ProductId = 16755231477,
			Image = "rbxthumb://type=Asset&id=".."16755231477".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_04 = {
			Id = "Pant_04",
			Name = "Pant",
			Price = 10,
			ProductId = 55315829,
			Image = "rbxthumb://type=Asset&id=".."55315829".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		
		Pant_05 = {
			Id = "Pant_05",
			Name = "Pant",
			Price = 7,
			ProductId = 16756607356,
			Image = "rbxthumb://type=Asset&id=".."16756607356".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_06 = {
			Id = "Pant_06",
			Name = "Pant",
			Price = 5,
			ProductId = 6825076864,
			Image = "rbxthumb://type=Asset&id=".."6825076864".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_07 = {
			Id = "Pant_07",
			Name = "Pant",
			Price = 7,
			ProductId = 16795868670,
			Image = "rbxthumb://type=Asset&id=".."16795868670".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_08 = {
			Id = "Pant_08",
			Name = "Pant",
			Price = 7,
			ProductId = 17111258462,
			Image = "rbxthumb://type=Asset&id=".."17111258462".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_09 = {
			Id = "Pant_09",
			Name = "Pant",
			Price = 5,
			ProductId = 17824081540,
			Image = "rbxthumb://type=Asset&id=".."17824081540".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_10 = {
			Id = "Pant_10",
			Name = "Pant",
			Price = 5,
			ProductId = 16925998038,
			Image = "rbxthumb://type=Asset&id=".."16925998038".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_11 = {
			Id = "Pant_11",
			Name = "Pant",
			Price = 5,
			ProductId = 17507100734,
			Image = "rbxthumb://type=Asset&id=".."16925998038".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		Pant_12 = {
			Id = "Pant_12",
			Name = "Pant",
			Price = 5,
			ProductId = 16863829080,
			Image = "rbxthumb://type=Asset&id=".."16863829080".."&w=150&h=150",
			CurrencyType = Constants.CurrencyTypes.Robux,
			InventoryType = Constants.InventoryType.Styling,
			ProductType = Enum.InfoType.Asset,
			ItemType = Constants.ItemType.Pant,
		},
		
	}
end
